### ISSUE TITLE
#7 HEROKU: Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by JeffKnowlesJr** [JeffKnowlesJr/mern-dev-connector#7]
> client@0.1.0 build
> react-scripts build       
> Creating an optimized production build...
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/tmp/build_900494f9/client/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:417:16)
>     at handleParseError (/tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:471:10)
>     at /tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:503:5
>     at /tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:358:12
>     at /tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at iterateNormalLoaders (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
>     at /tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:236:3
>     at runSyncOrAsync (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
>     at iterateNormalLoaders (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
>     at Array.<anonymous> (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
>     at Storage.finished (/tmp/build_900494f9/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
>     at /tmp/build_900494f9/client/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
> /tmp/build_900494f9/client/node_modules/react-scripts/scripts/build.js:19
>   throw err;
>   ^
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/tmp/build_900494f9/client/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:417:16)
>     at /tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:452:10
>     at /tmp/build_900494f9/client/node_modules/webpack/lib/NormalModule.js:323:13
>     at /tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
>     at /tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
>     at context.callback (/tmp/build_900494f9/client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
>     at /tmp/build_900494f9/client/node_modules/babel-loader/lib/index.js:59:103 {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> }
> Node.js v18.13.0
> -----> Build failed

**Comment by JeffKnowlesJr** [comment]
> jeffk@RAIDER MINGW64 ~/workspace/jeffknowlesjr/mern-dev-connector (main)
> $ heroku stack --app devconnector
> === ⬢ devconnector Available Stacks
>   container
>   heroku-18
>   heroku-20
> * heroku-22
> 
> jeffk@RAIDER MINGW64 ~/workspace/jeffknowlesjr/mern-dev-connector (main)
> $ heroku stack:set heroku-18 --app devconnector
> Setting stack to heroku-18... done                                                                                                   
>  !    The Heroku-18 stack is deprecated and reaches end-of-life on April 30th, 2023. Please upgrade to a newer stack as soon as      
>  !    possible: https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq
